### ISSUE TITLE
plan for kibana 6.x

### ISSUE THREAD

**Issue by tatdatpham** [dlumbrer/kbn_network#47]
Thank for good plugin!
Do you have plan for kibana 6.x. Thanks!

**Comment by dlumbrer** [comment]
Thanks @tatdatpham.

Of course, Im working to migrate it to 6.X!! I hope in the next days have a release

**Comment by nadz-goldman** [comment]
@dlumbrer , thanks for this plugin and your work on it
Everybody hopes that you give us new version for Kibana 6x =)

**Comment by purplesrl** [comment]
+1

**Comment by geertn444** [comment]
+1

**Comment by omarix** [comment]
+1

**Comment by ErikvdVen** [comment]
Any updates on how your progress goes on migrating the plugin to 6.x? Cause so far I was able to migrate the plugin, except for the controller... Still working on that part. I'm able to load the plugin and create a visualization, but I'm not able to actually render the visualisation, because the console shows errors about certain parts of objects are undefined. E.g. ` var buckets = resp.aggregations[firstFieldAggId].buckets;` , "resp"object  doesn't contain a key called "aggregations", and I guess it used to...

**Comment by dlumbrer** [comment]
I'm working on these @ErikvdVen , exactly in the 6-dev branch!

I have problems with the structure of the data retrieved of ES 6, it is completly different... I have to parse all the data again!

**Update**: Integrated in the menu

![network_vis_6](https://user-images.githubusercontent.com/9249232/33941364-a7162cda-e012-11e7-8c58-b4f81988c6ac.png)

**Comment by ErikvdVen** [comment]
Thanks for the update, after forking your repo again I did notice the 6-dev branch indeed (after opening it in GitKraken) :+1: Looking forward to the release :)

**Comment by dlumbrer** [comment]
Hope soon!! ;)

**Comment by dlumbrer** [comment]
**Update**:

Parsing for the Node-Node type is ready!.


Now it's time to Node-Relation and that's it...

**Comment by purplesrl** [comment]
Great news :)

**Comment by dlumbrer** [comment]
Finally I finished the migration, and here is the new release for Kibana 6!

https://github.com/dlumbrer/kbn_network/releases/tag/6.0.X

**Comment by omarix** [comment]
Thank very much
